name: PyInstaller Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --clean --onefile LinSoTrackerTemplateChecker.py
        mv dist/LinSoTrackerTemplateChecker dist/LinSoTrackerTemplateChecker.exe

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: LinSoTrackerTemplateChecker
        path: dist/LinSoTrackerTemplateChecker.exe