name: PyInstaller Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --clean --onefile LinSoTrackerTemplateChecker.py
        
    - name: Get Tag Name and Commit Message
      uses: actions/github-script@v4
      id: tag_and_commit
      with:
        script: |
          const tagName = context.payload.ref.replace('refs/tags/', '');
          const commitSha = context.payload.head_commit.id;
          const commitMsg = context.payload.head_commit.message;
          console.log(tagName);
          console.log(commitSha);
          console.log(commitMsg);
          return { tagName, commitSha, commitMsg };

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_and_commit.outputs.commitSha }}
        release_name: ${{ steps.tag_and_commit.outputs.commitSha }}
        body: ${{ steps.tag_and_commit.outputs.commitMsg }}
        draft: false
        prerelease: false
      if: startsWith(github.ref, 'refs/tags/')

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: LinSoTrackerTemplateChecker
        path: dist/LinSoTrackerTemplateChecker.exe
